package com.example.coursework.model.enums;

public enum MangaGenre {
    SHOUNEN, SHOUJO, SEINEN, JOSEI, KODOMO, YAOI, YURI, ISEKAI, FANTASY, ACTION, ADVENTURE, COMEDY, DRAMA, HORROR, MYSTERY, ROMANCE, SCI_FI, THRILLER
}
